### ISSUE TITLE
Errors when submitting build to App Store

### ISSUE THREAD

**Issue by laurent-humbert** [teads/TeadsSDK-iOS#105]
HI,

I got the SDK to work fine in the Simulator, but when uploading the build to TestFlight I get a bunch of errors.

I don't use CocoaPods, I just added the framework TeadsSDK-iOS-master/TeadsSDK.framework  (version 4.1.6) to my project.

This is with Xcode 10.1.

Any ideas ?

Thanks

Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary 
is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Specifically, we found the following unsupported architectures in your binary:

x86_64
i386
For more information, see Technical Q&A QA1707 at: http://developer.apple.com/iphone/library/qa/qa2010/qa1707.html.

Invalid Segment Alignment - The app binary at 'XXXXX.app/Frameworks/TeadsSDK.framework/TeadsSDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Encryption Info - The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

Though you are not required to fix the following issues, we wanted to make you aware of them:

Non-PIE Binary - The executable 'Payload/XXXXX.app/Frameworks/TeadsSDK.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Best regards,

The App Store Team

**Comment by HugoGresse** [comment]
Hi Laurent,
We'll investigate and get back to you soon. 

Hugo

**Comment by jeremygrosjean** [comment]
Hi Laurent,
It seemed to be linked to https://mobile.teads.tv/sdk/documentation/ios/ad-format/inread#archive-known-issues

**Comment by laurent-humbert** [comment]
Thanks I’ll give this guy’s script a try

L
