### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by laurent-humbert** [teads/TeadsSDK-iOS#107]
Hi there,

I'm upgrading to Swift 5 and I'm getting the following error message when importing the Teads Framework:

Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

**Comment by HugoGresse** [comment]
Hi Laurent,

Thanks for reporting this. We'll work on Swift 5 compatiblity and hopefully we'll have something ready very soon. 
We'll keep you updated with the progress.

**Comment by HugoGresse** [comment]
Hi Laurent,

Some update: we are in the process of automatising the Swift 5 & Swift 4 pod release. We'll be able to release separate Teads SDK pod for specific swift version after that, probably by EOW or next week.

**Comment by MaximeLM** [comment]
Hi,

The error reported here happens after updating to Xcode 10.2, even without migrating to Swift 5.

Would it be possible to provide a framework built with Xcode 10.2 (swift 4.2 or 5) as a workaround until you complete your automatisation?

**Comment by jeremygrosjean** [comment]
Hello guys,
as the automation is taking some times I've provided a version compiled with the last XCode you can find it here https://github.com/teads/TeadsSDK-iOS/tree/master/TeadsSDK-Xcode10.2/TeadsSDK.framework
Thanks for your patience.

**Comment by MaximeLM** [comment]
I confirm the workaround works. Thanks!

**Comment by laurent-humbert** [comment]
Thanks! New version works fine here.

**Comment by HugoGresse** [comment]
Perfect, thanks for the feedback!
Closing this, don't hesitate to reopen it if needed.

**Comment by painhapp** [comment]
@HugoGresse Thank you - It is working when I add the framework as "embedded binary", however when trying to upload I get the following signing issues. What's the proper way to include the framework manually instead of pods?
When I use it as "Linked framework and library" i am unable to start the app "Reason: image not found"
![Screenshot 2019-04-08 at 13 28 16](https://user-images.githubusercontent.com/4242986/55720988-7c19a280-5a02-11e9-86e8-972bf9516c83.png)

**Comment by jeremygrosjean** [comment]
Hey,
I think this part of the documentation can help you: https://mobile.teads.tv/sdk/documentation/ios/ad-format/inread#archive-known-issues

**Comment by laurent-humbert** [comment]
<img width="376" alt="Screenshot 2019-08-26 at 16 39 19" src="https://user-images.githubusercontent.com/19427074/63698914-18144100-c820-11e9-8195-9059da04da97.png">

Just downloaded the Xcode 1 beta 6, and I'm getting this error message.

**Comment by laurent-humbert** [comment]
Hi,

Could you do the same for Swift 5.1 ?

Thanks;

L
