### ISSUE TITLE
Library not loaded: @rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by sallenhandong** [teads/TeadsSDK-iOS#109]
when i create new peoject,build failed;
xcode_version:10.1

dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/mac/Library/Developer/CoreSimulator/Devices/7DC90D20-ECC8-409E-9341-73B277E7E86C/data/Containers/Bundle/Application/3D0D8ACE-FD7D-440F-A5E9-71BA76BD8DEC/teads.app/Frameworks/TeadsSDK.framework/TeadsSDK
  Reason: image not found

**Comment by HugoGresse** [comment]
Hi, I think you already contacted Teads by email. Closing this in favor of the email thread. 
Don't hesitate to reopen this if needed.
