### ISSUE TITLE
Swift 5.1

### ISSUE THREAD

**Issue by daveluong** [teads/TeadsSDK-iOS#112]
Hi,

Could you provide TeadsSDK compiled with Swift 5.1 in Xcode 11 beta? 
It's for testing purpose so we only need it to compile our project.

**Comment by jeremygrosjean** [comment]
Hello,

I've just installed the xcode beta, here's the SDK https://we.tl/t-BAgtQFq8qt
I don't have tested yet so be aware of that.

Best,
J
