### ISSUE TITLE
Update TeadsSDK for Swift 5.1 & Xcode 11

### ISSUE THREAD

**Issue by richardxyx** [teads/TeadsSDK-iOS#113]
Hi, we'd like to use the SDK with Swift 5.1 & Xcode 11 and were wondering when Teads will add support. It would be most helpful if you could provide a separate branch like you did for Xcode 10.2 😊

**Comment by HugoGresse** [comment]
Hi Richard,
Teads SDK 2.4.5 is available for Swift 5.1 [here](https://we.tl/t-BAgtQFq8qt)
This version has not been tested in production yet. 

We'll switch the default pod on this version later on.

**Comment by maxkattner** [comment]
Hi Hugo,
Is it possible to have this build also available on a branch in this repo? It would help our workflow very much when working on iOS 13 features if we only had to switch dependency branches. Of course we wouldn’t (and couldn’t) release with that version.

Thanks a lot for your assistance!

**Comment by jeremygrosjean** [comment]
Hello guys,
just made a branch with the framework compiled with the new XCode https://github.com/teads/TeadsSDK-iOS/tree/Swift5
Is that good for you?

**Comment by richardxyx** [comment]
Hi Jeremy,
Thank you for providing the branch, this makes things a lot easier for us. Looking forward to the full release.

**Comment by richardxyx** [comment]
Hello @HugoGresse & @jeremygrosjean,

as Apple released the new [Xcode 11 beta 3](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_3_release_notes), we noticed that the binary on the branch is not compatible with the latest beta anymore. It would help us a lot if you could recompile the SDK with the latest Xcode beta and push it to the same branch as earlier.

Thank you for your help in this matter!

**Comment by HugoGresse** [comment]
Hi Richard,
We'll provide an update binary either this week or next week.

**Comment by HugoGresse** [comment]
We've updated the framework using XCode beta3, you can either find it on the branch `xcode11b3` or [here](https://www.dropbox.com/s/7k0lyvhmxu437lo/TeadsSDK.framework%20-%20xcobe11beta3.zip?dl=1).

**Comment by vincentsaluzzo** [comment]
Hi @richardxyx 

You can find a SDK build with Xcode 11b3 on branch [xcode11b3](https://github.com/teads/TeadsSDK-iOS/tree/xcode11b3).

**Comment by richardxyx** [comment]
Thank you for your assistance @HugoGresse & @vincentsaluzz.

**Comment by richardxyx** [comment]
Hello @HugoGresse, we would appreciate if you could provide us with an updated branch compiled with the latest [Xcode beta](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_5_release_notes) so we can continue developing our app on the latest beta.

**Comment by HugoGresse** [comment]
Hi Richard, I'll loop with the team and get back to you.

**Comment by HugoGresse** [comment]
So we are waiting for the RC or the final XCode 11 to release any Teads framework supporting XCode 11.
Let us know if you need anything more.

**Comment by richardxyx** [comment]
Hi Hugo, we would greatly appreciate it if you could recompile and push to one of the existing branches (or a new one) so we can continue using the latest Xcode beta before the GM release in September.

**Comment by oliviersanz** [comment]
Hello @HugoGresse,

I'm an iOS developer working for Eurosport and we also really need an update of Teads framework so we can test that everything is ok with the latest XCode beta (5), before the GM release.
Do you think it could be possible to release an update soon ?

Thank you !

**Comment by vincentsaluzzo** [comment]
Hello @oliviersanz & @richardxyx 

We will take a look this week and come to you when it will ok.

Best

**Comment by maxkattner** [comment]
Hi @vincentsaluzzo, were you able to get everything running with beta 6? We would love to continue our efforts on preparing iOS 13 support and are kinda dependent on your regular beta updates. Let me know if you need any assistance.

Thank you!

**Comment by laurent-humbert** [comment]
With Xcode beta 6 I get

"Compiled module was created by an older version of the compiler; rebuild 'TeadsSDK' and try again:"

**Comment by vincentsaluzzo** [comment]
Hello there,

We will try to provide you a version with latest Xcode beta soon.

Best

**Comment by vincentsaluzzo** [comment]
You could find a version builded with β6 in https://github.com/teads/TeadsSDK-iOS/tree/xcode11b6

**Comment by maxkattner** [comment]
@vincentsaluzzo Thank you! However, we are still getting the error `Compiled module was created by an older version of the compiler` for the TeadsSDK. Can you please check if you really used the Swift 5.1 compiler shipped in Xcode 11 Beta 6?

**Comment by vincentsaluzzo** [comment]
My bad @maxkattner, I've upload the wrong SDK. I've just pushing the good one. Could you retry ?

**Comment by maxkattner** [comment]
Thank you @vincentsaluzzo, we can get back to the beta fun now. :)

**Comment by matsoft90** [comment]
Does it work with the GM seed?

**Comment by laurent-humbert** [comment]
Yes the built with b6 seems to compile and work fine with the Xcode 11 GM

**Comment by andr3a88** [comment]
Hi, with the version _xcode11b6_ on Xcode 11.1 (11A1027) I still getting te error `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler`

**Comment by vincentsaluzzo** [comment]
There is no need to use this version anymore. Last version is compiled with Xcode 11 and ready for Swift 5.1
