### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.1 compiler

### ISSUE THREAD

**Issue by laurent-humbert** [teads/TeadsSDK-iOS#117]
Here we go again

**Comment by tapi** [comment]
I was just speaking with an Apple engineer about this. Apparently Module and ABI stability are not enabled by default. You need to turn it on in build settings.

"Build Libraries for Distribution"
<img width="935" alt="image" src="https://user-images.githubusercontent.com/455558/67802459-2ddcf700-fa59-11e9-8958-85b9cb5d0f9c.png">

@jeremygrosjean @ThibaudSE What are the chances of a 4.3.3 point release to fix this given that Xcode 11.2 is hopefully gonna drop in a day or less?

**Comment by elneruda** [comment]
Hi @laurent-humbert @tapi I've created a branch https://github.com/teads/TeadsSDK-iOS/tree/swift5_1_1 Xcode 11.2 compliant

**Comment by tapi** [comment]
Does it have Module Stability turned on?

**Comment by elneruda** [comment]
Module Stability is not activated, this change is planned in our roadmap

**Comment by fabianehlert** [comment]
Hi @elneruda :) Do you have an estimation when we can expect a Xcode 11.2 compatible release?

**Comment by elneruda** [comment]
Hi @fabianehlert, @laurent-humbert , @tapi we've just released [4.3.4 version](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.3.4) with Xcode 11.2 compatibility

**Comment by laurent-humbert** [comment]
Just switched to that version, now if I import TeadsSDK in a file this generates errors with the use of the '>' operator in that file.

Ambiguous operator declarations found for operator
Operator is not a known binary operator

Any ideas ?

**Comment by elneruda** [comment]
Hi @laurent-humbert a new version with fix is on the way

**Comment by elneruda** [comment]
@laurent-humbert new [version 4.3.5](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.3.5) has been release

**Comment by laurent-humbert** [comment]
Looks like version 4.3.5 fixes it 👍

**Comment by elneruda** [comment]
Great! closing issue

**Comment by tapi** [comment]
Xcode 11.4 has the same issue, When might we expect Module Stability?

**Comment by elneruda** [comment]
Hello @tapi As I commented [here](https://github.com/teads/TeadsSDK-iOS/issues/120#issuecomment-607306540),  a new version that will support Xcode 11.4 will be released soon
