### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by MaximeLM** [teads/TeadsSDK-iOS#119]
We are receiving this warning when uploading our apps to AppStore Connect:

> We identified one or more issues with a recent delivery for your app, APP_NAME. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020 : https://developer.apple.com/news/?id=12232019b

TeadsSDK is using UIWebView (verified with `strings TeadsSDK.framework/TeadsSDK | grep UIWebView`). Are you planning a fix for this issue?

**Comment by gmadouas-teads** [comment]
Thank you to raise this issue, it come from our third party Open Measurement we will contact them and add this update to our roadmap.

**Comment by gmadouas-teads** [comment]
We have upgraded the Open Measurement framework (IAB) in our SDK version 4.5.0 and according to them it fix your issue, can you tell us the version of your teads SDK ?

**Comment by MaximeLM** [comment]
I am using version 4.5.0. The warning may come from an other dependency of our app.

**Comment by pkordal** [comment]
Hi @gmadouas-teads ,

When doing grep over your SDK in version 4.7.7 i am getting several findings of UIWebView. We are pretty much sure warning from Apple on UIWebView usage is going from your SDK, as we have many apps and only one has TeadsSDK onboard, and this one produces e-mail from Apple.

`pkordal-nm:Pods pkordal$ grep -nirs 'uiwebview' *
Binary file Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds matches
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13460:-[OMIDTeadstvUIWebViewJSExecutor initWithWebView:]
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13461:-[OMIDTeadstvUIWebViewJSExecutor supportBackgroundThread]
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13462:-[OMIDTeadstvUIWebViewJSExecutor jsEnvironment]
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13463:-[OMIDTeadstvUIWebViewJSExecutor injectJavaScriptFromString:]
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13464:-[OMIDTeadstvUIWebViewJSExecutor .cxx_destruct]
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13465:_OBJC_IVAR_$_OMIDTeadstvUIWebViewJSExecutor._webView
TeadsSDK/TeadsSDK.framework/F96DCE41-EF75-39D7-AB8E-0F3C195E3346.bcsymbolmap:13466:/Users/travis/build/InteractiveAdvertisingBureau/Open-Measurement-SDKiOS/temp/AppVerificationLibrary/OMIDUIWebViewJSExecutor.m
Binary file TeadsSDK/TeadsSDK.framework/TeadsSDK matches
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14154:-[OMIDTeadstvUIWebViewJSExecutor initWithWebView:]
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14155:-[OMIDTeadstvUIWebViewJSExecutor supportBackgroundThread]
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14156:-[OMIDTeadstvUIWebViewJSExecutor jsEnvironment]
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14157:-[OMIDTeadstvUIWebViewJSExecutor injectJavaScriptFromString:]
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14158:-[OMIDTeadstvUIWebViewJSExecutor .cxx_destruct]
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14159:_OBJC_IVAR_$_OMIDTeadstvUIWebViewJSExecutor._webView
TeadsSDK/TeadsSDK.framework/90CEE546-B7DD-3D45-A153-C963CDAAA77A.bcsymbolmap:14160:/Users/travis/build/InteractiveAdvertisingBureau/Open-Measurement-SDKiOS/temp/AppVerificationLibrary/OMIDUIWebViewJSExecutor.m
TeadsSDK/TeadsSDK.framework/Headers/OMIDAdSession.h:42: * -[UIWebViewDelegate webViewDidFinishLoad:]).  Alternatively, if an implementation can receive an
TeadsSDK/TeadsSDK.framework/Headers/OMIDAdSessionContext.h:24: * @param webView The webView responsible for serving the ad content. Must be a UIWebView or WKWebView instance. The receiver holds a weak reference only.`

**Comment by gmadouas-teads** [comment]
Hi @pkordal,
it's a known issue with a viewability third party that we are integrating. We are working as we speak on updating it. We will keep you posted on our progress.

**Comment by andreipetrea** [comment]
@gmadouas-teads 

Do you have an ETA for this?

Since the deadline for the UIWebView removal is December 2020, we would like to be prepared as soon as possible.

**Comment by elneruda** [comment]
Hello @andreipetrea we're planning to release a new version next week, we'll keep you posted

**Comment by elneruda** [comment]
Hello @MaximeLM @pkordal @andreipetrea we've just released a [new version ](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.8.0)including latest OM SDK Version (all UIWebView references have been removed)

**Comment by andreipetrea** [comment]
Thanks @elneruda
