### ISSUE TITLE
Xcode 11.4 / Swift 5.1 incompatible

### ISSUE THREAD

**Issue by RealBug** [teads/TeadsSDK-iOS#120]
Hi,

Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler
FYI, with cocoapoad 1.9.1, you can use XCFramework.

- TeadsSDK (= 4.6.1)
- GoogleMobileAdsMediationTeads (4.6.1):

Thx

**Comment by elneruda** [comment]
Hello @RealBug, sorry for inconvenience, we are working to support Xcode latest version, we are also planning to enable [ABI](https://swift.org/blog/abi-stability-and-more/) on a future release, this is part of our roadmap

**Comment by RealBug** [comment]
@elneruda Ok perfect, thx

**Comment by swernerus** [comment]
Hello, is there a workaround in the meantime?

This prevents us from building the app.

**Comment by tapi** [comment]
@elneruda is there an ETA for this?

**Comment by elneruda** [comment]
Hello @tapi we're planning to release a new version (Xcode 11.4 / swift 5.2 compatible) next week.

**Comment by elneruda** [comment]
Hello @tapi @swernerus @RealBug new version [4.6.2](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.6.2) has been released, this version supports ABI stability.

**Comment by tapi** [comment]
![](https://media.giphy.com/media/k9qu4GDdGVDLa/giphy.gif)

**Comment by tapi** [comment]
Not seeing it on cocoapods yet, did it not get pushed or is the CDN just being slow to update?

**Comment by tapi** [comment]
given that it shows up on search im going to assume CDN. Thanks

**Comment by elneruda** [comment]
@tapi is TeadsSDK available on [cocoapods](https://github.com/CocoaPods/Specs/blob/master/Specs/f/2/1/TeadsSDK/4.6.2/TeadsSDK.podspec.json) for you ?

**Comment by tapi** [comment]
Yeah just took a bit to get to the CDN. Saw this when I pushed the latest version of the 1Password pod

**Comment by elneruda** [comment]
Great ! closing issue
