### ISSUE TITLE
bootstrap.js

### ISSUE THREAD

**Issue by laurent-humbert** [teads/TeadsSDK-iOS#122]
I get the message in the output log

"Impossible de lire les données car le format n’est pas correct."

It disappears if I remove the call to

self.webSync?.injectJS()

but then I get no ads.

Looks like the bootstrap.js has a problem parsing a JSON or something like that.

Any ideas ?

This is with the latest version of the SDK

Thanks;

**Comment by jeremygrosjean** [comment]
Hello Laurent,
sorry for the delay. I am indeed seeing this warning but it does work. I will investigate to remove this warning. Are you sure that your pid is a test placement?

**Comment by laurent-humbert** [comment]
Yes in the simulator the pid is 84242

**Comment by jeremygrosjean** [comment]
Do you still have the issue? I was not able to reproduce.

**Comment by elneruda** [comment]
Hello @laurent-humbert so you still have issue ?

**Comment by laurent-humbert** [comment]
Nope, using 4.7.5 and I still have this 
"The data couldn’t be read because it isn’t in the correct format."
warning in the log

**Comment by laurent-humbert** [comment]
Still there. I noticed I don't get this error message if I call settings.enableValidationMode(), but obviously this isn't a workaround.

**Comment by elneruda** [comment]
Hello @laurent-humbert, 

This console log message comes from JSON decoding, it's due to misreading data file but doesn't affect user's ad experience nor host application itself
Indeed, validation mode bypass this JSON evaluation but as you said, this can't be a workaround
We will fix misreading to not throw this warning anymore on a next release

**Comment by laurent-humbert** [comment]
👍

**Comment by elneruda** [comment]
Hello @laurent-humbert we've just released a new [SDK version ](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.7.8) fixing JSON misreading and therefore log warn `The data couldn’t be read because it isn’t in the correct format.`

**Comment by laurent-humbert** [comment]
Hurray! Thanks
