### ISSUE TITLE
Crash when configure upgrading TeadsSDKPrevious (4.2.5) to TeadsSDK (4.7.2)

### ISSUE THREAD

**Issue by charliefancelli** [teads/TeadsSDK-iOS#125]
Hi,

We have a crash when initialise your SDK on upgrading app.

Previous app use TeadsSDKPrevious (4.2.5) and we upgrade to TeadsSDK (4.7.2).

Crash occurs on `Teads.configure()` => `Thread 1: EXC_BREAKPOINT (code=1, subcode=0x108a3d230)`

Regards,

**Comment by elneruda** [comment]
Hello @charliefancelli 

Thank you for submitting issue, can you please forward full exception stack to help us investigate
For information, a newest and more stable [version](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.7.3) is available

**Comment by elneruda** [comment]
Hello @charliefancelli, do you still have issue ?

**Comment by charliefancelli** [comment]
Hi, your 4.7.3 fix the issue

**Comment by elneruda** [comment]
great! thanks for your feedback @charliefancelli
