### ISSUE TITLE
TCF2.0

### ISSUE THREAD

**Issue by laurent-humbert** [teads/TeadsSDK-iOS#127]
Hi there,

Is version 4.7.5 TCF 2.0 compatible ?

We display the consent form using the latest AdMob SDK (7.64), but are the consent string etc  taken into account by the Teads SDK on iOS ?

Thanks

**Comment by ndahmani** [comment]
Hi @laurent-humbert 
Teads inAppSDK v4.7.5 is TCF v2.0 compatible.
As long as your CMP is IAB compliant, we should be able to retrieve all the information needed.

Please see the implementation guide here: 
https://support.teads.tv/support/solutions/articles/36000166727-privacy-consent-management-gdpr-ccpa-

We recommend validating the set up using the validation tool: 
https://support.teads.tv/support/solutions/articles/36000209100-validation-tool
Bests,

**Comment by laurent-humbert** [comment]
Thanks, I forgot about the validation tool. I did use it a while back, but now calling enableValidationMode() does nothing, I'm not getting the dialog with the url. I do get the ad though. Any ideas ?

**Comment by elneruda** [comment]
Do you use childViewController ? maybe AlertVC cannot present modally as SDK is not able to locate properly presentedVC

**Comment by laurent-humbert** [comment]
I haven't changed anything in the controllers etc... I don't know why enableValidationMode no longer works...

**Comment by laurent-humbert** [comment]
Well I left enableValidationMode and completely forgot about it, and last night, out of the blue the dialog popped-up, but just once.

**Comment by elneruda** [comment]
thanks for your reply @laurent-humbert were you able to perform validation checks ? 
in addition with popup dialog, you should be able to see in console log the alert message prompt
`**************************************
******* Teads SDK Validation ***********
To start the validation, open this page on your desktop:

https://sdkvalidation.teads.tv/XXXXXXX

Waiting for the first test to start...
**************************************`

if not this log should appear instead : `Teads: Could not find controller to present dialog`

Can you confirm you see one of these console logs

We're still investigating this issue

**Comment by laurent-humbert** [comment]
HI,

Nope, I'm not seeing any of these messages :-(

**Comment by elneruda** [comment]
great ! 
could you confirm you pass validation tool ? everything ok, including TCFv2 ?

**Comment by laurent-humbert** [comment]
Yes, everything OK 
<img width="340" alt="Screenshot 2020-09-10 at 14 08 55" src="https://user-images.githubusercontent.com/19427074/92727317-35ef0e00-f36f-11ea-998d-59c3394434e4.png">
