### ISSUE TITLE
Why are all the TeadsSDK.CommanderWebView(s) kept in the keyWindow?

### ISSUE THREAD

**Issue by andreipetrea** [teads/TeadsSDK-iOS#128]
Hi,

We have Teads SDK integrated in our app and I recently noticed that TeadsSDK is keeping all the TeadsSDK.CommanderWebView(s) in the keyWindow.

I made a test using the "TeadsSDK-iOS-4.7.5" sample app on an iPhone 11 PRO with iOS 13.7. 
Here's the scenario:
- run the Teads sample app
- tap on "inRead top implementation" cell
- tap back
- repeat the above 2 steps for multiple times
- from Xcode, tap on Debug View Hierarchy (see the below screenshot)

Is this expected?

<img width="1792" alt="Screenshot 2020-09-04 at 15 07 58" src="https://user-images.githubusercontent.com/983218/92254151-1c664600-eed9-11ea-8a7d-419c63325336.png">

**Comment by jeremygrosjean** [comment]
Hello Andrea,

thanks for your analyse. I think it's linked to a memory leak we've since resolved and will release and our next SDK.
I'm sorry for the inconvenience and will keep you updated on the release.

**Comment by andreipetrea** [comment]
Thank you for the quick response! I look forward to hearing from you.

**Comment by jeremygrosjean** [comment]
Hey Andrei,
we just released a new SDK 4.7.7 that should resolved your issue.
Maybe you will have trouble to get it for some times because of the cocoa pod cache but it's there.
Can you tell me if it's working for you?

**Comment by andreipetrea** [comment]
I confirm that once I stop requesting Teads ads and the existing ad views are released, TeadsSDK.CommanderWebView(s) are no longer present int UIWindow nor in memory.

Thank you!
