### ISSUE TITLE
Can't compile TeadsSDK using Xcode 12 - Beta 6

### ISSUE THREAD

**Issue by lugearma** [teads/TeadsSDK-iOS#129]
Hi, I've been trying to compile my app using Xcode 12 beta 6 and I'm getting this issue:

**Failed to build module 'TeadsSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'**

I have install TeadsSDK v. 4.7.5

Is there any way to avoid this ??

Thanks for your help.

**Comment by elneruda** [comment]
Hello @lugearma thank you for posting this issue, I've been testing simulator run and archive on Demo App with TeadsSDK 4.7.5 on Xcode 12b6 with no issue
For information TeadsSDK installation has been performed using cocoapods version `1.9.1`, how did you install TeadsSDK to your app ?

**Comment by elneruda** [comment]
I've edited scheme build configuration to `Release` and was able to reproduce the issue on simulator, but on device (iPhone X 11.3) it is running well
Can you specify how do you build/run your app ? It seems this issue happens on beta.

**Comment by lugearma** [comment]
Hi @elneruda, I installed Teads through cocoapods version 1.9.3 (`pod 'TeadsSDK', '4.7.5'`).
I was able to make it work switching the `Build Active Architecture Only` setting to `YES` in my release target. 
So I think that might be the issue, in my develop target it works well because that flag is `YES` but in it doesn't work in my production target, where the flag is `NO`

**Comment by lugearma** [comment]
@elneruda I tried using a device and as you said it works, but when I tried in a simulator it didn't the same issue is happening in my CI/CD system setup on bitrise.

**Comment by elneruda** [comment]
Hi @lugearma can you provide a sample app that I can test with ? 
What build configuration are you specifying when running on simulator ?

As I can see on Xcode 12 beta [release note ](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes) this could be a hint
_The Build Settings editor no longer includes the Valid Architectures build setting (VALID_ARCHS), and its use is discouraged. Instead, there is a new Excluded Architectures build setting (EXCLUDED_ARCHS). If a project includes VALID_ARCHS, the setting is displayed in the User-Defined section of the Build Settings editor. (15145028)_

**Comment by lugearma** [comment]
Hi @elneruda, I'm using the `Release` config, it works well in `Debug` but changing to `Release` it doesn't. 
Also I tried with the TeadsSDK demo and it fails for the same reason if I change the `Build Configuration` to `Release`.

**Comment by lugearma** [comment]
Apple will release iOS 14 tomorrow, I was waiting for a new beta version but that won't happen, i don't know what to do. :(

**Comment by elneruda** [comment]
Hello @lugearma despite running on simulator on `Release` are you able to create an archive of your app ? I've tested it on DemoApp with success. BTW we've just released a new [SDK version](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.7.8) with some improvements (does not cover simulator+release issue)

**Comment by elneruda** [comment]
hello @lugearma do you still have issue with Xcode 12 & TeadsSDK ?
If yes, can you try to add this hook to podfile could solve issue : 
`post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 arm64e armv7 armv7s"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "i386 x86_64"
  end
end`

let me know if it works for you
