### ISSUE TITLE
TeadsSDK checksum is different between team members

### ISSUE THREAD

**Issue by tahirmt** [teads/TeadsSDK-iOS#133]
We are on 4.6.2 and `pod install` produces a different checksum among team members so we end up having a diff when nothing is actually changed.

**Comment by elneruda** [comment]
Hello @tahirmt thank you for posting this issue, checksum resolution relies on cocoapods, maybe clear cocoapods cache on all dev stations. In fact I suggest to upgrade to our [latest SDK release](https://github.com/teads/TeadsSDK-iOS/releases/latest) which includes many fixes and improvements

**Comment by elneruda** [comment]
Hello @tahirmt do you still have issue ? Have you upgraded SDK version to latest ?

**Comment by tahirmt** [comment]
Hello @elneruda updating the SDK is not feasible at the moment but I did have my team clear Cocoapods cache but that didn't fix the issue.

**Comment by elneruda** [comment]
Hello @tahirmt this issue could come from cocoapod version directly, there's an issue filled [here](https://github.com/CocoaPods/CocoaPods/issues/8931)
Make sure you're using the same cocoapod version among team members.
The best way to get rid of checksum issue is to run this on all your team dev stations :
run `rm -rf Pods/` then `pod cache clean --all` and then `pod install`.

**Comment by tahirmt** [comment]
That issue has been marked fixed as of 1.8 we are on the current version. We did do a full cache clean and removed the pods directory too with a pod install. 

The reason I asked here is because we only get it for Teads. I'll see if updating Teads fixes it next week.

**Comment by elneruda** [comment]
Hello @tahirmt have you update Teads ? are you still encountering issue ?

**Comment by tahirmt** [comment]
Hi @elneruda we finally updated Teads today and we are no longer seeing this issue.
