### ISSUE TITLE
No action when user click on advertisements 

### ISSUE THREAD

**Issue by binodav** [teads/TeadsSDK-iOS#136]
I'm using SDK 4.7.8 build with Xcode 11.6.
My device running iOS 13.6.1

I integrated Teads Ads on both Android and iOS using **Standard Integration** but I noticed eCPM on iOS only half of eCPM on Android. While checking iOS integration, I found that when I click on ads view, nothing happen. By right, it should open the advertiser website. Only clicking on AdsChoices icon and the label "Ads by Teads", it open the browser to Teads website. Whilst testing with similar ads on Android, it did open the advertiser website.

I followed the iOS integration guide and also implemented this delegate below:

> func adBrowserWillOpen(_ ad: TFAAdView) -> UIViewController? {
>           return self
> }

I put a breakpoint at the above function but it never trigger, it only trigger when I click on AdsChoices icon and the label "Ads by Teads".

I enabled debug mode, and below log was recorded after I clicked on the ads, it seems trigger open browser function but nothing happen on my device:
> 2020-10-12 06:01:58 +0000 Teads: onClickThroughRequest
> 2020-10-12 06:01:58 +0000 Teads: JSEngine: openBrowser

I'm not sure if there's anything wrong with my integration.

**Comment by elneruda** [comment]
Hello @binodav, thank you for raising this issue, we are investigating on it.
Your integration seems to be correct.
Main cause of this issue seems to be some malformed URL string that can't be parsed as URL and therefore can't be opened in SFSafariViewController. We let you know when we fix issue.

**Comment by elneruda** [comment]
Hello @binodav, fix has been deployed on the fly (hosted configuration file) you should be able to click through now.
let me know if it's ok for you

**Comment by binodav** [comment]
Hello @elneruda. Thank you for your quick support. It's working perfectly now.

**Comment by elneruda** [comment]
Great! closing issue
