### ISSUE TITLE
[Question] iOS 14 and Xcode 12 support

### ISSUE THREAD

**Issue by andreipetrea** [teads/TeadsSDK-iOS#138]
We plan to build the app using Xcode 12 and we would like to know:
- when do you estimate to have a release with support for iOS 14 and Xcode 12?
- is it safe to build the app with Xcode 12 using the latest version of the Teads SDK - v4.7.8?

**Comment by vincentsaluzzo** [comment]
Hello @andreipetrea 

The last version of Teads SDK already support Xcode 12 and iOS 14. 
At our knowledge, is safe to use the last Xcode version with our latest SDK version.

Best

**Comment by andreipetrea** [comment]
Thank you!
