### ISSUE TITLE
App audio is interrupted when loading an ad

### ISSUE THREAD

**Issue by jilouc** [teads/TeadsSDK-iOS#140]
Our app plays some podcasts, we configure the audio session accordingly using

```swift
AVAudioSession.sharedInstance().setCategory(.playback, mode: .spokenAudio, policy: .longForm)
```

so that it's nicely integrated with other audio apps.

When loading an ad, we notice that the podcast is automatically being paused.

It seems that you're overriding the audio session category to `AVAudioSessionCategoryAmbient` in `SoundHandler.init(shouldHandleAudioSession:sumoLogManager:)` and deactivating the session in `SoundHandler.stopAudioSessionHandling()`

<img width="406" alt="Capture d’écran 2020-11-06 à 13 41 18" src="https://user-images.githubusercontent.com/612462/98367906-b4e28900-2036-11eb-9461-5cac5cf9fd94.png">

<img width="522" alt="Capture d’écran 2020-11-06 à 13 42 11" src="https://user-images.githubusercontent.com/612462/98367894-b14f0200-2036-11eb-94c5-a3ea77421f89.png">

This issue is reproducible in your demo project **on device (it won't happen on the simulator)**, just by modifying RootViewController.swift, adding 

```swift
    var audioPlayer: AVPlayer!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        hasTeadsArticleNavigationBar = false
        collectionView.allowsMultipleSelection = true
        
        try? AVAudioSession.sharedInstance().setCategory(.playback, mode: .spokenAudio, policy: .longFormAudio)
        try? AVAudioSession.sharedInstance().setActive(true)
        let item = AVPlayerItem(asset: AVURLAsset(url: URL(string: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_5MG.mp3")!))
        self.audioPlayer = AVPlayer(playerItem: item)
        self.audioPlayer.play()
    }
```

as soon as you open any item (table view, web view…), the audio stops.

**Comment by jilouc** [comment]
We managed to prevent this behaviour by swizzling `-[AVAudioSession setActive:withOptions:error:]` and `-[AVAudioSession setCategory:mode:options:error:]` to prevent the override when the podcast is playing.  
It works but it's ugly.

**Comment by jeremygrosjean** [comment]
Hello Jean-Luc,
did you check that part of the documentation https://support.teads.tv/support/solutions/articles/36000187283-audio-mix-management-ios-only- ?
I think it could help you

**Comment by jilouc** [comment]
I saw that but I thought it would not work because we can't set `.mixWithOthers`, but I'll give it a try.

**Comment by jilouc** [comment]
Ok so that's on me, looks like I've misunderstood the documentation on this point.
Good news and thank you for your quick reply!

**Comment by ciriac** [comment]
@jilouc I know this is an old issue, but we're facing the same problem right now. I downloaded the sample app and modified the snippet above to include `.mixWithOthers`. Audio plays fine when the sample is loaded but as soon as you navigate to the scrollview example there's no audio anymore. Am I doing something wrong?

```
    var audioPlayer: AVPlayer!

    override func viewDidLoad() {
        super.viewDidLoad()
        hasTeadsArticleNavigationBar = false

        try? AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: .mixWithOthers)
        try? AVAudioSession.sharedInstance().setActive(true)
        let item = AVPlayerItem(asset: AVURLAsset(url: URL(string: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3")!))
        audioPlayer = AVPlayer(playerItem: item)
        audioPlayer.play()
    }
```

**Comment by jilouc** [comment]
Calling `disableTeadsAudioSessionManagement()` on the `TeadsAdSettings` object did the trick for us.

**Comment by github-paul-nicolas** [comment]
Hello @ciriac thank you for reaching us, as said @jilouc (thank you for your replies) you can specify to [handle the audio management by yourself](https://teads.github.io/TeadsSDK-iOS/5.0.20/documentation/teadssdk/teadsadplacementsettings/disableteadsaudiosessionmanagement()), here is the dedicated documentation section: [Audio Management](https://support.teads.tv/support/solutions/articles/36000314762-audio-management)

**Comment by ciriac** [comment]
@jilouc Thanks. 

@github-paul-nicolas So simply setting `. mixWithOthers` no longer does the trick?

**Comment by ciriac** [comment]
@github-paul-nicolas sure. From the documentation I understood that if you have your `AVAudioSession` category's option set to `mixWithOthers` the audio would simply mix and not stop all other sounds from playing before an ad is loaded.

Using the snipper for the example app that I posted earlier, this is no longer the case. The snippet is setting the category to `mixWithOthers` but as soon as you navigate to an example with an ad the sound from the video player stops.

> If you are using an audio session with a category that is non-mixable, all sound from other applications (eg: Spotify) would be stopped when an ad will start playing (even an ad without sound). This is due to Apple's default behavior with a video player.
\
To prevent that and preserve optimal user experience, please make sure that your audio session category is mixable. You can add mixWithOthers from AVAudioSession.CategoryOptions in some category (like .playback).

**Comment by github-paul-nicolas** [comment]
Hello @ciriac 

I've made some tests implementing your snippet on this branch [audio_playback](https://github.com/teads/TeadsSDK-iOS/tree/audio_playback)
**Configuration**:
Format: `inRead`
Provider: `Direct`
Creative: `Landscape`
Integration: `ScrollView`

Steps reproduced on simulator and real iPhone device:
1. ensure the volume is up and the mute button is off
2. when ScrollView appears, wait for the song to load and play
3. scroll to the ad
4. unmute ad: the song and the ad audio are mixed

The loaded song is continuing to play regardless the ad is muted or not

Also reproduced with these steps:
1. ensure the volume is up and the mute button is off
2. when ScrollView appears
3. scroll to the ad
5. unmute ad: ad audio is playing
6. once the song (mp3) is loaded and starts to play: the song and the ad audio are mixed

Are you experiencing the same behavior when testing this branch `audio_playback`?

**Comment by ciriac** [comment]
@github-paul-nicolas Thanks for this. I think I know what's happening. My device was muted.

So if the device is muted and there's an ad in the scrollview:
- No song audio

If the device is muted and there's _no ad_ in the scrollview (comment out line 37:InReadDirectScrollViewController):
- Yes song audio

**Comment by github-antoine-barrault** [comment]
@ciriac can we consider this closed or do you still have an issue?

**Comment by ciriac** [comment]
@github-antoine-barrault you can close it, thanks!

**Comment by github-paul-nicolas** [comment]
I'm deleting the `audio_playback`, thank you for your feedback @ciriac
