### ISSUE TITLE
Simulator ARM architecture 

### ISSUE THREAD

**Issue by elneruda** [teads/TeadsSDK-iOS#142]
## Xcode 12 Excluded Architecture

Our third party viewability solution is unfortunately not yet compatible with ARM Simulator Architecture, we'll handle this architecture when available.

**Comment by tahirmt** [comment]
@elneruda any update on this?

**Comment by elneruda** [comment]
Hello @tahirmt we're dealing with our partner to have more visibility on this topic

**Comment by elneruda** [comment]
Hello @tahirmt we're planning to release a new version of SDK including `arm64` support for simulator next week, I'll keep you posted

**Comment by tahirmt** [comment]
@elneruda oh awesome! Thank you for the update.

**Comment by elneruda** [comment]
Hello @tahirmt, we've just released a new [version of SDK](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.8.3) which supports `arm64` architecture for simulator 🎉. This release is shipped as **xcframework**, you'll need cocoapods v1.9 minimum to integrate, or you can use Swift Package Manager as we've just introduced SPM distribution for **TeadsSDK**

**Comment by tahirmt** [comment]
Hello @elneruda thank you so much! 🎉

**Comment by elneruda** [comment]
Hello @tahirmt SDK v4.8.3 doesn't support `arm64` simulator (build issue), the [new version 4.8.4](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.8.4) now full supports `arm64`, sorry for the back and forth

**Comment by tahirmt** [comment]
Thanks for the heads up. We hadn't updated yet.
