### ISSUE TITLE
TeadsSDK and GoogleMobileAdsMediationTeads throw errors when linting for cocoapods

### ISSUE THREAD

**Issue by kevinjameshunt** [teads/TeadsSDK-iOS#149]
Our organization uses cocoapods to build modular internal frameworks that wrap third-party SDKs (such as Teads, Google, etc). Unfortunately, while attempting to wrap the TeadsSDK into our own internal framework and integrate it into our automated CI/testing/etc, we run into the following error when running `pod lib lint --allow-warnings --sources='https://github.com/CocoaPods/Specs'`

`- ERROR | [iOS] xcodebuild:  GoogleMobileAdsMediationTeads/TeadsAdMobAdapter/GADMAdapterTeadsBanner.swift:10:8: error: failed to build module 'TeadsSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'`

This may be related to #142, but it severely limits our ability to integrate the TeadsSDK into our automated build/testing flow.

**Comment by vincentsaluzzo** [comment]
Hi @kevinjameshunt, which version of our adapter did you used?
Could you paste the part of Podfile related to Teads SDK?

**Comment by kevinjameshunt** [comment]
From my Podfile.lock: 
`- GoogleMobileAdsMediationTeads (4.8.0):
    - Google-Mobile-Ads-SDK (>= 7.59)
    - TeadsSDK (= 4.8.0)`

**Comment by elneruda** [comment]
Hello @kevinjameshunt as you said, this could be related to #142, we will release a new version next week including `arm64` support for simulator

**Comment by elneruda** [comment]
Hello @kevinjameshunt, we've just released a new [version of SDK](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.8.3) which supports `arm64` architecture for simulator. Podfile has been cleanup as we don't need to exclude architecture anymore. Let me know if this release fix issue

**Comment by elneruda** [comment]
Hello @kevinjameshunt do you still have issue ? without feedback I will close issue

**Comment by elneruda** [comment]
issue has no feedback since 28 days, closing it
