### ISSUE TITLE
[iOS 15][Xcode 13 beta] Crash for EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by andr3a88** [teads/TeadsSDK-iOS#155]
Hi,

while testing my app with Xcode 13 beta I have a crash due to bad access. The same implementation with xcode 12 still works.

To confirm the problem I tried with the example app from this repository, the problem occurs in the integration with the web view.

Xcode does not give me any stack trace or log in the debugger related to the crash

![bad](https://user-images.githubusercontent.com/6755254/127326428-79ef0ef6-7133-43d5-b30d-093486f3dbb4.png)

![demo](https://user-images.githubusercontent.com/6755254/127326418-2bcc635c-d2dd-418f-8ba2-006da3766f5c.png)

**Comment by elneruda** [comment]
thank you @andr3a88 for submitting issue, can you specify which xcode and iOS version are involved specifically ? 
Side note: on previous iOS beta versions (iOS 14, 13..) we've already experienced some strange behaviours until the latest beta or GM to have back the expected behaviour

**Comment by andr3a88** [comment]
@elneruda I recognized the issue the first time with Xcode 13 beta 3 and iOS 15 beta 3. Today I update to Xcode 13.0 beta 4 (13A5201i) and iOS beta 4 the problem is still present. I think it's something related to WebKit maybe because of the beta version.

**Comment by elneruda** [comment]
Hello @andr3a88 we're able to reproduce issue on iOS 15, we are currently investigating and will keep you updated.
For now you can still use TeadsSDK with Xcode 13 and iOS 14

**Comment by elneruda** [comment]
hello @andr3a88 we've just released a [new SDK version](https://github.com/teads/TeadsSDK-iOS/releases/tag/v4.8.8) which fix issue running Xcode 13 beta and iOS 15 beta.

let me know if it works for you

**Comment by andr3a88** [comment]
@elneruda now with the versione `4.8.8` it works. thank you!
