### ISSUE TITLE
Fix: Cannot find protocol declaration for 'TFAAdDelegate

### ISSUE THREAD

**Issue by nihp** [teads/TeadsSDK-iOS#157]
Fix: Cannot find protocol declaration for 'TFAAdDelegate

How can I upgrade my Teads Sdk and How can i check the version which was available now in the Xcode? 

<img width="390" alt="Screenshot 2021-08-05 at 10 36 25 AM" src="https://user-images.githubusercontent.com/36992338/128293970-26779d3d-8565-46c0-9fd4-2d8ac7fe5496.png">

**Comment by jeremygrosjean** [comment]
Hey,
can you give me more details, what SDK version do you want to use? 
What's the version that is causing you issue?

**Comment by jesphinpt** [comment]
@jeremygrosjean I am new to this. In my code, I have Teads.framework. Not using pods. I have objective-c app.

How can I know the version of this in my Xcode. I have checked the info.plist but there is no version specified.

**Comment by nihp** [comment]
I am not using the latest version for sure with arm64 update. But I have the arm64 support m1 machine. Here I can't able to find the Teads framework version in info.plist file. 

Could you please let me know how the Teads sdk will be updated. How can I update the framework in my project.

Note: I am not using pod. Using Objective-c with frameworks 

Using the import as below:

`#import <TeadsSDK/TeadsSDK.h>`

**Comment by jeremygrosjean** [comment]
Is there a particular reason why you don't want to use cocoapods?
Is your project full objective-C? If so I advise you to create at least one file in swift in your project it could help.

Where did you get the framework from this repository in TeadsSDK.xcframework?

**Comment by nihp** [comment]
No, I don't have any particular reason.

Now I have TeadsSDK.framework file in my app. But also have other xcframeworks file too.

**Comment by jeremygrosjean** [comment]
You can just add a new file and set swift file when you create it. It should ask you to add a header, you need to say yes.

**Comment by nihp** [comment]
@jeremygrosjean Could you please let e know how can I check the version in the code. 

My app is objective-c but i have seen the compile source have some swift files. Could you please let me know the above sdk updation is done by adding the git url in my app. It shows the swift dependency in my Xcode. Then what needs to be done.

Also shall I need to change to import as well?

Clarification: Does the TeadsSDK has the Objective-c support or only swift projects

**Comment by jeremygrosjean** [comment]
The Teads SDK cannot work with a 100% objective C project but if there is one swift class in the project it will work.

Are you using SPM with an objc projet? I strongly advise you to use cocoapod. I think it will make your life easier.

**Comment by jeremygrosjean** [comment]
Without any response of your part I considered that it's not a problem anymore.
