### ISSUE TITLE
Using SDK in projects makes about 209 warnings

### ISSUE THREAD

**Issue by mArm-ch** [teads/TeadsSDK-iOS#19]
The absolute path on the developer's local computer (nikolai) is set in the framework.
![capture d ecran 2015-10-29 a 09 54 23](https://cloud.githubusercontent.com/assets/3752160/10849362/c26dcde4-7f20-11e5-8d9c-901be57ef73a.png)

**Comment by ibrahimennafaa** [comment]
fixed in [v1.6.1](https://github.com/teads/TeadsSDK-iOS/tree/v1.6.1)
