### ISSUE TITLE
When fetching with Swift Package Manager, 403 error occurs while trying to download 'AppLovinSDK'

### ISSUE THREAD

**Issue by marlinblue** [teads/TeadsSDK-iOS#231]
hi.
I'm trying to add TeadsSDK to my project through Swift Package Manager.
However, an AppLovinSDK download error occurs as shown below.

error: failed downloading ‘https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/AppLovinSDK-12.2.1.xcframework.zip’ which is required by binary target ‘AppLovinSDK’: badResponseStatusCode(403)

'https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/AppLovinSDK-12.2.1.xcframework.zip'
It is possible to download by accessing this link with a web browser.

Are there any known related issues?

**Comment by github-lucas-bon** [comment]
Hello @marlinblue thanks for sharing, we are going to address this issue asap, we let you know.

**Comment by github-richard-depierre** [comment]
Hi @marlinblue,

Thanks for reaching out! I'm trying to help you troubleshoot the AppLovinSDK download error you're encountering when adding the TeadsSDK through Swift Package Manager. 

To get a better understanding of the situation, could you please provide some additional information:

* **TeadsSDK Version:** Which specific version of the TeadsSDK are you trying to install? Knowing the exact version can help identify any known compatibility issues.

* **Screenshots:** If possible, could you share screenshots of the following:
    * The error message you're seeing in Xcode.
    * The "Swift Packages" tab in Xcode where you've added the TeadsSDK dependency.

This information will help me pinpoint the cause of the error and suggest potential solutions.

Additionally, although you mentioned being able to download the AppLovinSDK framework manually through a web browser, it's generally not recommended to bypass the Swift Package Manager for dependencies. It's best practice to manage all dependencies through the package manager to ensure consistency and avoid potential conflicts.

I'll be happy to assist further once I have more details about your specific setup.

**Comment by blick9** [comment]
Hello @github-lucas-bon 

sorry for late reply. I am a fellow developer of the issue author.
This issue was not covered by our company's network security policy.
It has been resolved now.
thank you.
