### ISSUE TITLE
Apple Privacy updates 

### ISSUE THREAD

**Issue by stancho-stanchev** [teads/TeadsSDK-iOS#232]
Hi Teads Team, 
Apple started checking the Privacy Manifest files on the 13 March for each AppStore submission. 
For now it is only a warning, but after the 1st of May we will be blocked if this is still not resolved.

Could you please kindly look into this as our app is dependent on your SDK!

We are currently using `TeadsSDK 5.1.0`

We got this message from the App Review team: 

---
ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the
"Frameworks/TeadsSDK.framework/TeadsSDK" file contains "C617.1" as the value for a NSPrivacyAccessedAP|TypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAP|Category UserDefaults category. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, values for NSPrivacyAccessedAP|TypeReasons keys in your app's privacy manifest must be valid reason codes for the corresponding API category.
---

**Comment by adlibsv** [comment]
We received the same warning.

**Comment by v-andreipetrea** [comment]
We received the same warning.

**Comment by adlibsv** [comment]
@stancho-stanchev Are you still receiving this warning? In our case, on the latest submission we are no longer seeing this warning. We fixed the other warnings we had but no changes on Teads SDK side.

**Comment by v-andreipetrea** [comment]
@stancho-stanchev Are you still receiving this warning? In our case, on the latest submission we are no longer seeing this warning. We fixed the other warnings we had but no changes on Teads SDK side.
