### ISSUE TITLE
5.1.1 Release not updating the google mobile ads SDK as stated in the release notes

### ISSUE THREAD

**Issue by stancho-stanchev** [teads/TeadsSDK-iOS#239]
Hello Teads team

@github-richard-depierre 

In your latest release 5.1.1 you specify that: `Updated Google-Mobile-Ads-SDK to v11.2.0.`

But after updating the package to 5.1.1 on our side the google mobile ads has not updated to the 11.2.0 and the Package.swift file does not have support for such version. 

This is an update which we need quite urgent as our app also depends on the Google-Mobile-Ads-SDK and we need to update to 11.2.0 for the Privacy manifest support, but not being able to because of the Teads SDK not yet supporting this version. 

Would you be so kind to check and rectify this.

Many thanks

**Comment by github-richard-depierre** [comment]
Hi @stancho-stanchev , I've just completed the update to version 5.1.1. Everything should be functioning properly now. Please go ahead and update, and let me know if you encounter any issues.
