### ISSUE TITLE
The signing certificate has been revoked.

### ISSUE THREAD

**Issue by loinsir** [teads/TeadsSDK-iOS#253]
<img width=30% src="https://github.com/user-attachments/assets/ed817b13-4147-454f-81b9-ce3dd99bae4a">

<img width=30% src="https://github.com/user-attachments/assets/500d9c21-ddc4-48cc-a7bf-7c5e7b1917e7">

Hello, @github-richard-depierre 

I'm facing an issue where the message 'The signing certificate has been revoked.' appears, preventing me from compiling. 

I suspect the certificate might have been renewed. Could you help me resolve this error?

This version is 5.1.8. with Xcode16.

**Comment by github-richard-depierre** [comment]
Hello @loinsir,

Thank you for reaching out.

We’re aware of the issue related to the signing certificate and will release a new version during the day to update the signing certificate. Please keep an eye out for the update and let us know if you encounter any further issues after applying it.

Thank you for your patience.

Best,
Richard Depierre

**Comment by github-richard-depierre** [comment]
Hello @loinsir,

Version 5.1.9 has been released, addressing the issue with the signing certificate. Please update to the latest version and let us know if the issue persists.

Thank you for your understanding and cooperation.

Best regards,
Richard Depierre

**Comment by loinsir** [comment]
Thank you! @github-richard-depierre

All issues have been resolved. Thank you for your hard work:)
