### ISSUE TITLE
Conflict between TeadsReachability and Reachability in 1.6.5

### ISSUE THREAD

**Issue by mArm-ch** [teads/TeadsSDK-iOS#32]
Hello. 
There is still a conflict on "_kReachabilityChangedNotification" with 1.6.5

Here's the log : 
duplicate symbol _kReachabilityChangedNotification in:
    /Users/dan/Library/Developer/Xcode/DerivedData/Elle_Horoscope-cbrwiabitmhqshbjuxeeyfvzgmrs/Build/Intermediates/Elle Horoscope.build/Debug-iphoneos/Elle Horoscope.build/Objects-normal/arm64/Reachability.o
    Elle Horoscope/Classes/Externals/TeadsSDK.framework/TeadsSDK(TeadsReachability.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Niko-r** [comment]
Hello @mArm-ch ,

v1.6.6 has been released to fix this https://github.com/teads/TeadsSDK-iOS/releases/tag/v1.6.6

Let me know if everything is ok for you, so we can close this issue.

Thank you

**Comment by ibrahimennafaa** [comment]
Same as https://github.com/teads/TeadsSDK-iOS/issues/23

Reported as fixed in 1.6.6
