### ISSUE TITLE
retain cycle 

### ISSUE THREAD

**Issue by kambala-decapitator** [teads/TeadsSDK-iOS#50]
https://github.com/facebook/FBRetainCycleDetector reports that there's a retain cycle:

```
    "-> TeadsAdWebView ",
    "-> _bridge -> TeadsWebViewJavascriptBridge ",
    "-> _base -> TeadsWebViewJavascriptBridgeBase ",
    "-> _messageHandlers -> __NSDictionaryM ",
    "-> __NSMallocBlock__ "
```

Probably a block stored in property strongly captures `self` or so.

**Comment by Niko-r** [comment]
Thanks for reporting, we will take a look into this.

**Comment by Niko-r** [comment]
#93
