### ISSUE TITLE
sample not working

### ISSUE THREAD

**Issue by simsimmal** [teads/TeadsSDK-iOS#65]
After unsuccessfully trying to integrate the TeadsSDK in our project, i gave the sample project a look and a try. Same error: TeadsSDKDemo[67988:14406941] Teads_Error: __20-[TeadsAd requestAd]_block_invoke [Line 673] No ads available

**Comment by Niko-r** [comment]
Hi,

this simply means there is no advertisements related to the PID dedicated to the demo app. 
We will reactivate them so that you can try our SDK.

For the integration of our SDK in your project you should contact your publisher manager so that you can have your own PID for your application.

**Comment by simsimmal** [comment]
Well,
a out of the box working sample would be great!

Our ads department was in contact with teads, and they already provided PIDs, one for Android, one for iOS. My Android coworking did contact the teads support, with no success so far, i think she filed a ticket which is open and unanswered jet. But i think teads wrote her its a bug and its forwarded to the developers!!!!!! 

So no you are telling me its simply not configured neither for the PIDs we got from your company nor in the sample project. My coworker gets no help but a pending ticket and i get this info here on github in the issue page of the iOS sample???

I thought you were trying to sell something? Provide a test/debug flag on your SDK and deliver some demo ads for heavens sake. I would have taken the PIDs from the demo project to test my implementation but....

I'll contact my coworker in the ads department first thing tomorrow morning. Can he relate ads to the PIDs? 

Please let me know if the sample PIDs are working again.

**Comment by Niko-r** [comment]
Hello @simsimmal ,

The ads in the sample are available again. This wasn't an issue from the SDK nor the app, so you just have to launch the demo app you already have.

Regarding the PIDs, you misunderstood what I was telling you : the configuration of PID used in our demo app has been changed by mistake on our server. So while we would put it back to active, I was simply proposing you to use the PID you already have been given for your application so you could test the demo app right away.

I am truly sorry that you coworker did not get any feedback yet. 
Unfortunately, please understand that with just your nickname on Github we won't be able to help you.

If you encounter technical issue on our SDKs, you can contact support-sdk@teads.tv

Thank you

**Comment by simsimmal** [comment]
Thank You,

i did get you from the beginning, the problem was, our PIDs were also not booked with ads. But a coworker of you fixed that yesterday. And thank you for activating the sample PIDs. It was bad luck to get PIDs without ads and then check out the sample project which also had no ads configured..... Now we are happily receiving ads and will start to test them soon. 

Thanks
