### ISSUE TITLE
ld: 11 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by Bobrovsky** [teads/TeadsSDK-iOS#74]
H,

I upgraded to TeadsSDK 2.7.1 via CocoaPods. I am using Xcode 7 at the moment.

When I try to build my project I get the following linker errors. There were no issues until the upgrade. I tried to clean the project. I removed DerivedData. Nothing helps.

What might cause the issue and what can I do to resolve it?

```
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog.ready in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog._pendingEventsArray in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog.amount in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog.shouldSendErrors in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog.appsIds in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsRemoteLog.collectorUrl in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_CLASS_$_TeadsRemoteLog in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_METACLASS_$_TeadsRemoteLog in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsRemoteLog.o)
duplicate symbol _OBJC_IVAR_$_TeadsLog.debugLevel in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsLog.o)
duplicate symbol _OBJC_CLASS_$_TeadsLog in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsLog.o)
duplicate symbol _OBJC_METACLASS_$_TeadsLog in:
    /Users/sergeybobrovsky/Documents/myprojectname/Pods/TeadsSDK/TeadsSDKDemo/TeadsSDK.framework/TeadsSDK(TeadsLog.o)
ld: 11 duplicate symbols for architecture arm64
```

**Comment by Niko-r** [comment]
Hi @Bobrovsky , 

This seems to be caused by the fact of having two copies of our SDK in your project.
Can you check for your project/subproject and if one shouldn't be there?

Also, are you linking our `TeadsSDK.framework` directly in your project? make sure this is *not* the case.

Let us know if this solves things.

Thank you

**Comment by nejrazulic** [comment]
We have the same problem to integrate each version of TeadsSDK >= 2.6.0 using cocoapods version 1.1.1. Version 2.5.6 works fine. 

All worked earlier with cocoapods 0.35.0. 

XCode version is 8.3.

The error and log are the same as reported above: 11 duplicate symbols for architecture x86_64.

**Comment by Niko-r** [comment]
Thank you for these informations @nejrazulic 

We will come back with a solution asap

**Comment by Niko-r** [comment]
Can you tell me the following

- What is in your Podfile?
- In your Build Settings, what is in `Other Linker Flags`?

CocoaPods last version is 1.2.1, does it happen with this version too?

Thank you

**Comment by Bobrovsky** [comment]
@Niko-r 

I have checked and I do not see any Teads SDK related files outside of the Pods project. I do not link to TeadsSDK.framework. 

I tried to rollback to 2.5.6 using `pod 'TeadsSDK', '2.5.6'` in my Podfile and the issue is gone. It probably proves I do not have duplicates in my workspace. 

I am using CocoaPods 1.2.1 now and it does not help with version 2.7.1 of the SDK. In fact, using 2.6 and 2.7 also leads to the duplicate symbols issue.

My Podfile contains the following
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

abstract_target 'ios' do
    pod 'Google-Mobile-Ads-SDK'
    pod 'TeadsSDK'
    pod 'HockeySDK'
	
    target 'My Target Name'
end
```

And here are the Other Linker Flags
`$(inherited) -ObjC -l"c++" -l"xml2" -l"z" -framework "AVFoundation" -framework "AdSupport" -framework "AudioToolbox" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CoreVideo" -framework "Foundation" -framework "GLKit" -framework "GoogleMobileAds" -framework "HockeySDK" -framework "MediaPlayer" -framework "MessageUI" -framework "MobileCoreServices" -framework "OpenGLES" -framework "QuartzCore" -framework "QuickLook" -framework "Security" -framework "StoreKit" -framework "SystemConfiguration" -framework "TeadsSDK" -framework "UIKit" -weak_framework "AdSupport" -weak_framework "JavaScriptCore" -weak_framework "SafariServices" -weak_framework "WebKit"`

**Comment by Niko-r** [comment]
Thank you for this feedback @Bobrovsky 
This is a strange situation that doesn't happen in all projects..

Dumb questions. If not already done, can you:
- Clean your project
- Clean your build folder
- Remove/comment `pod 'TeadsSDK'` line in your `Podfile`, run `pod install` to remove completely our SDK from your project
- Add `TeadsSDK` again in your `Podfile` and install it again

We are continuing investigations on our side, let us know is these actions changed something.

**Comment by Bobrovsky** [comment]
@Niko-r 
Thank you for your suggestions but they didn't worked. 

I cleaned the project. Removed everything from DerivedData and cleaned the Trash. I commented out the SDk in Podfile and ran `pod install`. I saw the SDK was removed from the Pods project. I un-commented the SDK and ran `pod install` again. I reopened and rebuilt the project. 

Unfortunately, I got the same 11 duplicate symbols.

**Comment by Niko-r** [comment]
New question: are you able to reproduce this issue on a new project too?

**Comment by Bobrovsky** [comment]
I can not reproduce the issue with a new project.

**Comment by Bobrovsky** [comment]
I can reproduce the issue by simply replacing TeadsSDK.framework and TeadsSDKResources.bundle with latest versions. 

I mean, if I take a project with Teads SDK 2.5.6 (which builds just fine) and replace TeadsSDK.framework and TeadsSDKResources.bundle with files from Teads SDK 2.7.1 I will have the 11 duplicate symbols. 

So, the issue is probably not related to changes in config, project or other similar files. 

@Niko-r  Do you have any other ideas for what can I do to resolve the issue?

**Comment by Niko-r** [comment]
Can you try the following (make a backup of your project first):

1. Add `post_install` in your `Podfile`
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

post_install do |installer_representation|
    installer_representation. pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited), PodsDummy_Pods=SomeOtherNamePodsDummy_Pods'
        end
    end
end

....
```

2. Delete:
    -  `Pods` folder
    - `Podfile.lock`
    - `YourProject.xcworkspace`

3. Run `pod install`

**Comment by Bobrovsky** [comment]
Unfortunately, adding the post_install didn't help.

**Comment by Niko-r** [comment]
Can you try the update with this beta version of the SDK? (like what you tried earlier by replacing TeadsSDK.framework and TeadsSDKResources.bundle)

 [TeadsSDK-V2.7.2b.zip](https://github.com/teads/TeadsSDK-iOS/files/995958/TeadsSDK-V2.7.2b.zip)

**Comment by Bobrovsky** [comment]
With the 2.7.2b issue is gone. Thank you.

Do you know when this code will be available through CocoaPods? Is it safe to use the 2.7.2b from the above zip in production?

**Comment by Niko-r** [comment]
No don't use it. I'll make a release asap for this and I'll ping you here when the release is available.

Also, what about you @nejrazulic and the proposed solutions above?

**Comment by nejrazulic** [comment]
Sorry for delayed response.

We tried proposed solutions with post_install and project clean. It didn't work.

**Comment by Niko-r** [comment]
Thank you @nejrazulic . Does the beta version 2.7.2 provided above solves things?

**Comment by Niko-r** [comment]
Hi @Bobrovsky v2.7.2 has been released. It should be available from CocoaPods when there cache is updated.

Thank you

**Comment by Bobrovsky** [comment]
@Niko-r  Thank you. Using 2.7.2 from CocoaPods resolves the issue.

**Comment by nejrazulic** [comment]
2.7.2 works without any problems. Thank you a lot @Niko-r.

**Comment by Niko-r** [comment]
Great news! Thank you both of you for your patience
