### ISSUE TITLE
Possible issue on iPhone X Simulator

### ISSUE THREAD

**Issue by neobeppe** [teads/TeadsSDK-iOS#83]
Testing our app on Xcode 9 GM with iPhone X Simulator, the are experiencing a crash on:

[TeadsNetworkMonitor getNetworkTypeByStatusBar]

________________________________________

`MyApp[71757:10530075] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStatusBar_Modern 0x7fd86dc05700> valueForUndefinedKey:]: this class is not key value coding-compliant for the key foregroundView.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bf221cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102c97f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bf22119 -[NSException raise] + 9
	3   Foundation                          0x0000000105e8cae6 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 226
	4   Foundation                          0x0000000105db8500 -[NSObject(NSKeyValueCoding) valueForKey:] + 284
	5   MyApp                        0x0000000101a5992a -[TeadsNetworkMonitor getNetworkTypeByStatusBar] + 130
	6   MyApp                        0x0000000101a5978f -[TeadsNetworkMonitor getNetworkStandardType] + 17
	7   MyApp                        0x0000000101a5952b +[TeadsUtil hasNetwork] + 60
	8   MyApp                        0x0000000101a20cbf -[TeadsAd load] + 410
	9   MyApp                        0x0000000101036b8b -[DCTeadsViewController reloadAdv] + 315
	10  MyApp                        0x0000000100f9dde3 -[DCAdvMediatorViewController reloadAdv] + 227
	11  MyApp                        0x0000000100f9da7d -[DCAdvMediatorViewController viewWillAppear:] + 333
	12  Apptimize                           0x0000000103a60c61 _logos_method$VCModCore$__ABT$viewWillAppear$ + 108
	13  UIKit                               0x000000010776e9b0 -[UIViewController _setViewAppearState:isAnimating:] + 444
	14  UIKit                               0x000000010776f011 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 265
	15  CoreFoundation                      0x000000010bf6233a -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 58
	16  UIKit                               0x000000010776ecbc -[UIViewController _setViewAppearState:isAnimating:] + 1224
	17  UIKit                               0x000000010776f011 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 265
	18  CoreFoundation                      0x000000010bf6233a -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 58
	19  UIKit                               0x000000010776ecbc -[UIViewController _setViewAppearState:isAnimating:] + 1224
	20  UIKit                               0x000000010776f245 -[UIViewController __viewWillAppear:] + 147
	21  UIKit                               0x00000001077a5f32 -[UINavigationController viewWillAppear:] + 445
	22  Apptimize                           0x0000000103a60c61 _logos_method$VCModCore$__ABT$viewWillAppear$ + 108
	23  UIKit                               0x000000010776e9b0 -[UIViewController _setViewAppearState:isAnimating:] + 444
	24  UIKit                               0x000000010776f245 -[UIViewController __viewWillAppear:] + 147
	25  UIKit                               0x00000001077cd6af -[UITabBarController viewWillAppear:] + 291
	26  MyApp                        0x0000000100ff2655 -[DCTabBarController viewWillAppear:] + 69
	27  Apptimize                           0x0000000103a60c61 _logos_method$VCModCore$__ABT$viewWillAppear$ + 108
	28  UIKit                               0x000000010776e9b0 -[UIViewController _setViewAppearState:isAnimating:] + 444
	29  UIKit                               0x000000010776f245 -[UIViewController __viewWillAppear:] + 147
	30  UIKit                               0x000000010773b881 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 1088
	31  UIKit                               0x00000001075d6c61 _runAfterCACommitDeferredBlocks + 318
	32  UIKit                               0x00000001075c530d _cleanUpAfterCAFlushAndRunDeferredBlocks + 280
	33  UIKit                               0x00000001075f5600 _afterCACommitHandler + 137
	34  CoreFoundation                      0x000000010bec4db7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	35  CoreFoundation                      0x000000010bec4d0e __CFRunLoopDoObservers + 430
	36  CoreFoundation                      0x000000010bea9324 __CFRunLoopRun + 1572
	37  CoreFoundation                      0x000000010bea8a89 CFRunLoopRunSpecific + 409
	38  GraphicsServices                    0x000000010ea369c6 GSEventRunModal + 62
	39  UIKit                               0x00000001075cad30 UIApplicationMain + 159
	40  MyApp                        0x0000000100e45bef main + 111
	41  libdyld.dylib                       0x000000010d0e9d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by Niko-r** [comment]
Hi @neobeppe thank you for reporting this, we will investigate on this

**Comment by Niko-r** [comment]
Fixed in v2.7.7 https://github.com/teads/TeadsSDK-iOS/pull/84
