### ISSUE TITLE
Delete row

### ISSUE THREAD

**Issue by lucascorrea** [teads/TeadsSDK-iOS#91]
I have one problem when I tried to use TeadsSDK on tableview.

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 1 from section 0 which only contains 1 rows before the update'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001106b4f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000115599deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001106b4dca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x0000000113c1aae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x0000000111c1d4e4 -[UITableView _endCellAnimationsWithContext:] + 4799
	5   UIKit                               0x0000000111c36632 -[UITableView _updateRowsAtIndexPaths:updateAction:withRowAnimation:] + 308
	6   ultimaterugby                       0x000000010e953186 -[TeadsInReadAdContainerTableView updateContainerLayout] + 158
	7   ultimaterugby                       0x000000010e97ab0d -[TeadsAd teadsAdDidResize] + 213
	8   ultimaterugby                       0x000000010e97e153 -[TeadsAdContent applyNewBodyViewRatio:] + 324
	9   ultimaterugby                       0x000000010e963790 -[TeadsNativeVideoAdContent mediaPlayerViewDidLoad:media:] + 509
	10  ultimaterugby                       0x000000010e984a72 __46-[TeadsMediaPlayerView loadVideo:withHeaders:]_block_invoke + 66
	11  libdispatch.dylib                   0x0000000115c43ef9 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000115c6449b _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000115c4c34b _dispatch_main_queue_callback_4CF + 1738
	14  CoreFoundation                      0x00000001106153e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00000001105d6939 __CFRunLoopRun + 2073
	16  CoreFoundation                      0x00000001105d5e98 CFRunLoopRunSpecific + 488
	17  GraphicsServices                    0x0000000116e89ad2 GSEventRunModal + 161
	18  UIKit                               0x0000000111afd676 UIApplicationMain + 171
	19  ultimaterugby                       0x000000010e3da28f main + 111
	20  libdyld.dylib                       0x0000000114a6192d start + 1`

**Comment by Niko-r** [comment]
I am closing this here, as the discussion is on our support mail.
